# Generated by Django 3.1.3 on 2020-12-06 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('att_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masterdata5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.IntegerField(verbose_name='Roll Number')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('class_name', models.CharField(max_length=100, verbose_name='Class Name')),
            ],
            options={
                'unique_together': {('roll_number', 'class_name')},
            },
        ),
        migrations.CreateModel(
            name='Mark_Attendance2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.IntegerField(verbose_name='Roll Number')),
                ('class_name', models.CharField(max_length=100, verbose_name='Class Name')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('time1', models.IntegerField()),
                ('ip_address', models.CharField(max_length=100)),
                ('date1', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=200)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll_no', to='att_app.masterdata5')),
            ],
            options={
                'unique_together': {('date1', 'ip_address'), ('roll_number', 'date1')},
            },
        ),
    ]
